
export enum UserRole {
  SUPER_ADMIN = 'admin',
  ADMIN = 'admin',
  SFD_ADMIN = 'sfd_admin',
  CLIENT = 'client',
  USER = 'user'
}

export const PERMISSIONS = {
  VALIDATE_SFD_FUNDS: 'validate_sfd_funds',
  AUDIT_SFD_ACCOUNTS: 'audit_sfd_accounts',
  GENERATE_REPORTS: 'generate_reports',
  MANAGE_USERS: 'manage_users',
  MANAGE_SFDS: 'manage_sfds',
  MANAGE_CLIENTS: 'manage_clients',
  MANAGE_LOANS: 'manage_loans',
  VALIDATE_CLIENT_ACCOUNTS: 'validate_client_accounts',
  CREATE_CLIENT_ACCOUNTS: 'create_client_accounts',
  MANAGE_SFD_LOANS: 'manage_sfd_loans',
  MANAGE_SFD_REPAYMENTS: 'manage_sfd_repayments',
  MANAGE_SFD_SAVINGS: 'manage_sfd_savings',
  ACCESS_SAVINGS: 'access_savings',
  DEPOSIT_SAVINGS: 'deposit_savings',
  WITHDRAW_SAVINGS: 'withdraw_savings',
  REQUEST_ADHESION: 'request_adhesion',
};

export const DEFAULT_ROLE_PERMISSIONS = {
  [UserRole.ADMIN]: [
    PERMISSIONS.VALIDATE_SFD_FUNDS,
    PERMISSIONS.AUDIT_SFD_ACCOUNTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_SFDS,
    PERMISSIONS.MANAGE_CLIENTS,
    PERMISSIONS.MANAGE_LOANS,
  ],
  [UserRole.SFD_ADMIN]: [
    PERMISSIONS.VALIDATE_CLIENT_ACCOUNTS,
    PERMISSIONS.CREATE_CLIENT_ACCOUNTS,
    PERMISSIONS.MANAGE_SFD_LOANS,
    PERMISSIONS.MANAGE_SFD_REPAYMENTS,
    PERMISSIONS.MANAGE_SFD_SAVINGS,
    PERMISSIONS.MANAGE_CLIENTS,
    PERMISSIONS.MANAGE_LOANS,
  ],
  [UserRole.CLIENT]: [
    PERMISSIONS.ACCESS_SAVINGS,
    PERMISSIONS.DEPOSIT_SAVINGS,
    PERMISSIONS.WITHDRAW_SAVINGS,
  ],
  [UserRole.USER]: [
    PERMISSIONS.REQUEST_ADHESION,
  ],
};
