
export enum UserRole {
  SUPER_ADMIN = 'admin',
  ADMIN = 'admin',
  SFD_ADMIN = 'sfd_admin',
  CLIENT = 'client',
  USER = 'user'
}

export const PERMISSIONS = {
  VALIDATE_SFD_FUNDS: 'validate_sfd_funds',
  AUDIT_SFD_ACCOUNTS: 'audit_sfd_accounts',
  GENERATE_REPORTS: 'generate_reports',
  MANAGE_USERS: 'manage_users',
  MANAGE_SFDS: 'manage_sfds',
  MANAGE_CLIENTS: 'manage_clients',
  MANAGE_LOANS: 'manage_loans',
  VALIDATE_CLIENT_ACCOUNTS: 'validate_client_accounts',
  CREATE_CLIENT_ACCOUNTS: 'create_client_accounts',
  MANAGE_SFD_LOANS: 'manage_sfd_loans',
  MANAGE_SFD_REPAYMENTS: 'manage_sfd_repayments',
  MANAGE_SFD_SAVINGS: 'manage_sfd_savings',
  ACCESS_SAVINGS: 'access_savings',
  DEPOSIT_SAVINGS: 'deposit_savings',
  WITHDRAW_SAVINGS: 'withdraw_savings',
  REQUEST_ADHESION: 'request_adhesion',
  
  // Add missing permissions
  PKI_MANAGEMENT: 'pki_management',
  CREATE_SFD: 'create_sfd',
  CREATE_SFD_ADMIN: 'create_sfd_admin',
  AUDIT_REPORTS: 'audit_reports',
  APPROVE_CLIENT_ADHESION: 'approve_client_adhesion',
  REJECT_CLIENT_ADHESION: 'reject_client_adhesion',
  REQUEST_LOAN: 'request_loan',
  REPAY_LOAN: 'repay_loan'
};

export const DEFAULT_ROLE_PERMISSIONS = {
  [UserRole.ADMIN]: [
    PERMISSIONS.VALIDATE_SFD_FUNDS,
    PERMISSIONS.AUDIT_SFD_ACCOUNTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_SFDS,
    PERMISSIONS.MANAGE_CLIENTS,
    PERMISSIONS.MANAGE_LOANS,
    PERMISSIONS.CREATE_SFD,
    PERMISSIONS.CREATE_SFD_ADMIN,
    PERMISSIONS.AUDIT_REPORTS,
    PERMISSIONS.PKI_MANAGEMENT,
  ],
  [UserRole.SFD_ADMIN]: [
    PERMISSIONS.VALIDATE_CLIENT_ACCOUNTS,
    PERMISSIONS.CREATE_CLIENT_ACCOUNTS,
    PERMISSIONS.MANAGE_SFD_LOANS,
    PERMISSIONS.MANAGE_SFD_REPAYMENTS,
    PERMISSIONS.MANAGE_SFD_SAVINGS,
    PERMISSIONS.MANAGE_CLIENTS,
    PERMISSIONS.MANAGE_LOANS,
    PERMISSIONS.APPROVE_CLIENT_ADHESION,
    PERMISSIONS.REJECT_CLIENT_ADHESION,
  ],
  [UserRole.CLIENT]: [
    PERMISSIONS.ACCESS_SAVINGS,
    PERMISSIONS.DEPOSIT_SAVINGS,
    PERMISSIONS.WITHDRAW_SAVINGS,
    PERMISSIONS.REQUEST_LOAN,
    PERMISSIONS.REPAY_LOAN,
  ],
  [UserRole.USER]: [
    PERMISSIONS.REQUEST_ADHESION,
  ],
};
