-- Add columns to sfds table for enhanced data
ALTER TABLE public.sfds 
ADD COLUMN IF NOT EXISTS clients_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS services JSONB DEFAULT '[]'::jsonb;

-- Insert real Malian SFDs with realistic data
INSERT INTO public.sfds (name, code, region, status, logo_url, phone, contact_email, description, clients_count, services, created_at, updated_at)
VALUES
  (
    'Kafo Jiginew',
    'KJ001',
    'Sikasso',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=KafoJiginew&backgroundColor=0D6A51',
    '+223 21 62 60 83',
    'contact@kafojiginew.ml',
    'La plus grande institution de microfinance du Mali, au service des agriculteurs et entrepreneurs depuis 1987',
    250000,
    '["Micro-crédit", "Épargne", "Assurance", "Mobile Money", "Transfert d''argent"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Nyèsigiso',
    'NY001',
    'Ségou',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=Nyesigiso&backgroundColor=FFAB2E',
    '+223 21 32 05 46',
    'info@nyesigiso.ml',
    'Institution de microfinance leader à Ségou, spécialisée dans le financement agricole et commercial',
    180000,
    '["Micro-crédit", "Épargne", "Crédit agricole", "Crédit commercial"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Soro Yiriwaso',
    'SY001',
    'Bamako',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=SoroYiriwaso&backgroundColor=176455',
    '+223 20 22 54 87',
    'contact@soroyiriwaso.ml',
    'SFD dynamique basée à Bamako, facilitant l''accès aux services financiers pour tous',
    120000,
    '["Micro-crédit", "Épargne", "Mobile Money", "Crédit jeunes"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'CVECA Baguinéda',
    'CV001',
    'Koulikoro',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=CVECABaguineda&backgroundColor=0D6A51',
    '+223 21 24 15 78',
    'cveca@baguineda.ml',
    'Caisse Villageoise d''Épargne et de Crédit Autogérée, soutenant le développement rural',
    95000,
    '["Épargne villageoise", "Crédit agricole", "Micro-crédit", "Formation"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Jemeni',
    'JM001',
    'Kayes',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=Jemeni&backgroundColor=FFAB2E',
    '+223 21 52 31 42',
    'info@jemeni.ml',
    'Institution de microfinance de référence dans la région de Kayes',
    85000,
    '["Micro-crédit", "Épargne", "Transfert international", "Crédit diaspora"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Yèrèwolo',
    'YW001',
    'Bamako',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=Yerewolo&backgroundColor=176455',
    '+223 20 29 17 63',
    'contact@yerewolo.ml',
    'SFD moderne offrant des solutions financières innovantes aux PME et particuliers',
    110000,
    '["Crédit PME", "Épargne", "Mobile Money", "Crédit express"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'BNDA',
    'BN001',
    'Bamako',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=BNDA&backgroundColor=0D6A51',
    '+223 20 22 41 55',
    'info@bnda.ml',
    'Banque Nationale de Développement Agricole, finançant le secteur agricole malien',
    150000,
    '["Crédit agricole", "Épargne", "Crédit équipement", "Assurance récolte"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Kondo Jigima',
    'KD001',
    'Koulikoro',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=KondoJigima&backgroundColor=FFAB2E',
    '+223 21 26 48 92',
    'contact@kondojigima.ml',
    'Institution solidaire accompagnant les communautés rurales de Koulikoro',
    72000,
    '["Micro-crédit", "Épargne solidaire", "Crédit groupe", "Alphabétisation financière"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Djiguiya SO',
    'DJ001',
    'Sikasso',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=DjiguiyaSO&backgroundColor=176455',
    '+223 21 62 15 39',
    'info@djiguiyaso.ml',
    'Partenaire de confiance des entrepreneurs et agriculteurs de Sikasso',
    88000,
    '["Micro-crédit", "Épargne", "Crédit stockage", "Crédit intrants"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'UACB',
    'UA001',
    'Bamako',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=UACB&backgroundColor=0D6A51',
    '+223 20 28 73 51',
    'contact@uacb.ml',
    'Union des Associations de Crédit du Bougounié, au service des communautés depuis 1994',
    65000,
    '["Crédit associatif", "Épargne", "Micro-crédit", "Appui technique"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Kokari',
    'KK001',
    'Mopti',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=Kokari&backgroundColor=FFAB2E',
    '+223 21 43 28 67',
    'info@kokari.ml',
    'Institution de microfinance dynamique dans la région de Mopti',
    58000,
    '["Micro-crédit", "Épargne", "Crédit pêche", "Crédit artisanat"]'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Faso Kanu',
    'FK001',
    'Koulikoro',
    'active',
    'https://api.dicebear.com/7.x/shapes/svg?seed=FasoKanu&backgroundColor=176455',
    '+223 21 25 94 38',
    'contact@fasokanu.ml',
    'SFD engagée dans l''inclusion financière des populations rurales',
    52000,
    '["Micro-crédit", "Épargne", "Crédit femmes", "Crédit jeunes"]'::jsonb,
    NOW(),
    NOW()
  )
ON CONFLICT (code) DO NOTHING;