// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnqysvnychmsockivqhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhucXlzdm55Y2htc29ja2l2cWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzAyNTgsImV4cCI6MjA1ODQwNjI1OH0.ENlPLNrFbgDyZhPIpUXHwt1IiElORGFeHpZItOxpBOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);